"""tables

Revision ID: c398a2b67d33
Revises: 
Create Date: 2023-03-17 00:48:12.660081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c398a2b67d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IGS_COURSE_ENQUIRY',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('followup_call_date', sa.Date(), nullable=True),
    sa.Column('followup_status', sa.String(), nullable=True),
    sa.Column('enquiry_by', sa.String(), nullable=True),
    sa.Column('mobile', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('fee_structure', sa.String(), nullable=True),
    sa.Column('experience_by', sa.String(), nullable=True),
    sa.Column('info_source', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IGS_COURSE_ENQUIRY_id'), 'IGS_COURSE_ENQUIRY', ['id'], unique=False)
    op.drop_index('ix_COURSE_ENQUIRY_id', table_name='COURSE_ENQUIRY')
    op.drop_table('COURSE_ENQUIRY')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('COURSE_ENQUIRY',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"COURSE_ENQUIRY_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('followup_call_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('followup_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enquiry_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fee_structure', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('info_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='COURSE_ENQUIRY_pkey')
    )
    op.create_index('ix_COURSE_ENQUIRY_id', 'COURSE_ENQUIRY', ['id'], unique=False)
    op.drop_index(op.f('ix_IGS_COURSE_ENQUIRY_id'), table_name='IGS_COURSE_ENQUIRY')
    op.drop_table('IGS_COURSE_ENQUIRY')
    # ### end Alembic commands ###
